package com.medical.medical.service;


import com.medical.medical.dao.DepartmentDAO;
import com.medical.medical.dao.DoctorRecordDAO;
import com.medical.medical.model.DoctorRecord;
import com.medical.medical.model.Employee;
import com.medical.medical.util.DateUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.sql.Date;
import java.util.List;

@Service
public class DoctorRecordService {
    @Autowired
    DoctorRecordDAO doctorRecordDAO;

    @Autowired
    EmployeeService employeeService;

    @Autowired
    DepartmentService departmentService;

    public List<DoctorRecord> getDoctorRecordList(int departmentId, Date scheduleDate, String scheduleName) {
        return doctorRecordDAO.getDoctorRecordList(departmentId,scheduleDate,scheduleName);
    }
// (doctor_id,department_id,schedule_date,morning,afternoon,night)
//自动生成doctorRecord表
    public int autoGenerated(){
        java.util.Date date = new java.util.Date();
        List<java.util.Date> weekdateList = DateUtil.returnNextWeekDate(new Date(date.getTime()),0);
        for (int i :departmentService.getAllDepartmentId()){
            List<Employee> employeeList = departmentService.selectChildrenById(i);
            for (Employee employee:employeeList){
                for (java.util.Date a : weekdateList){
                    DoctorRecord doctorRecord = new DoctorRecord();
                    doctorRecord.setDoctorId(employee.getId());
                    doctorRecord.setDepartmentId(i);
                    doctorRecord.setScheduleDate(new Date(a.getTime()));
                    doctorRecord.setMorning(1);
                    doctorRecord.setAfternoon(1);
                    doctorRecord.setNight(1);
                    doctorRecordDAO.add(doctorRecord);
                }


            }
        }
        return 1;
    }

    public int AutoGenerate(){
        try{
            deleteAllDoctorRecord();
            return autoGenerated();
        }catch (Exception e){
            System.out.println("已经加载过数据库");
        }finally {
            return 1;
        }
    }

    public int  deleteAllDoctorRecord(){
        return doctorRecordDAO.deleteAllDoctorRecord();
    }
}
